import { TCategoriesResponseData } from "@/shared/types/categories";

export const categories: TCategoriesResponseData = {
  categoriesMen: [
    {
      id: crypto.randomUUID(),
      slug: "trousers",
      name: "БРЮКИ И ДЖИНСЫ",
      list: [
        {
          id: crypto.randomUUID(),
          name: "БРЮКИ БАЛЛОНЫ",
          slug: "balloonTrousers",
          price: 9900,
          quantity: 10,
          imagesUrl: [
            "/images/product/men/trousers/balloonTrousers-1.jpg",
            "/images/product/men/trousers/balloonTrousers-2.jpg",
            "/images/product/men/trousers/balloonTrousers-3.jpg",
            "/images/product/men/trousers/balloonTrousers-4.jpg",
          ],
          previewImageUrl: "/images/product/men/trousers/balloonTrousers-5.jpg",
        },
        {
          id: crypto.randomUUID(),
          name: "БРЮКИ КАРГО",
          slug: "cargoPants",
          price: 9900,
          quantity: 10,
          imagesUrl: [
            "/images/product/men/trousers/cargoPants-1.jpg",
            "/images/product/men/trousers/cargoPants-2.jpg",
            "/images/product/men/trousers/cargoPants-3.jpg",
            "/images/product/men/trousers/cargoPants-4.jpg",
          ],
          previewImageUrl: "/images/product/men/trousers/cargoPants-5.jpg",
        },
        {
          id: crypto.randomUUID(),
          name: "БРЮКИ ПРЯМЫЕ",
          slug: "straightTrousers",
          price: 9900,
          quantity: 10,
          imagesUrl: [
            "/images/product/men/trousers/straightTrousers-1.jpg",
            "/images/product/men/trousers/straightTrousers-2.jpg",
            "/images/product/men/trousers/straightTrousers-3.jpg",
            "/images/product/men/trousers/straightTrousers-4.jpg",
          ],
          previewImageUrl:
            "/images/product/men/trousers/straightTrousers-5.jpg",
        },
        {
          id: crypto.randomUUID(),
          name: "БРЮКИ СПОРТИВНЫЕ",
          slug: "sportsTrousers",
          price: 9900,
          quantity: 10,
          imagesUrl: [
            "/images/product/men/trousers/sportsTrousers-1.jpg",
            "/images/product/men/trousers/sportsTrousers-2.jpg",
            "/images/product/men/trousers/sportsTrousers-3.jpg",
            "/images/product/men/trousers/sportsTrousers-4.jpg",
          ],
          previewImageUrl: "/images/product/men/trousers/sportsTrousers-5.jpg",
        },
      ],
      count: 4,
    },
    {
      id: crypto.randomUUID(),
      slug: "shirts",
      name: "РУБАШКИ",
      list: [
        {
          id: crypto.randomUUID(),
          name: "РУБАШКА ОВЕРСАЙЗ",
          slug: "oversizedShirt",
          price: 9900,
          quantity: 10,
          imagesUrl: [
            "/images/product/men/shirts/oversizedShirt-1.jpg",
            "/images/product/men/shirts/oversizedShirt-2.jpg",
            "/images/product/men/shirts/oversizedShirt-3.jpg",
            "/images/product/men/shirts/oversizedShirt-4.jpg",
          ],
          previewImageUrl: "/images/product/men/shirts/oversizedShirt-5.jpg",
        },
      ],
      count: 1,
    },
    {
      id: crypto.randomUUID(),
      slug: "t-shirts",
      name: "Майки и футболки",
      list: [
        {
          id: crypto.randomUUID(),
          name: "ФУТБОЛКА ОВЕРСАЙЗ",
          slug: "oversizedShirt",
          price: 9900,
          quantity: 10,
          imagesUrl: [
            "/images/product/men/t-shirts/oversizedTShirt-1.jpg",
            "/images/product/men/t-shirts/oversizedTShirt-2.jpg",
            "/images/product/men/t-shirts/oversizedTShirt-3.jpg",
            "/images/product/men/t-shirts/oversizedTShirt-4.jpg",
          ],
          previewImageUrl: "/images/product/men/t-shirts/oversizedTShirt-5.jpg",
        },
        {
          id: crypto.randomUUID(),
          name: "МАЙКА ВЯЗАНАЯ",
          slug: "knittedTShirt",
          price: 9900,
          quantity: 10,
          imagesUrl: [
            "/images/product/men/t-shirts/knittedTShirt-1.jpg",
            "/images/product/men/t-shirts/knittedTShirt-2.jpg",
          ],
          previewImageUrl: "/images/product/men/t-shirts/knittedTShirt-3.jpg",
        },
        {
          id: crypto.randomUUID(),
          name: "ФУТБОЛКА МНОГОСЛОЙНАЯ",
          slug: "multiLayeredTShirt",
          price: 9900,
          quantity: 10,
          imagesUrl: [
            "/images/product/men/t-shirts/multiLayeredTShirt-1.jpg",
            "/images/product/men/t-shirts/multiLayeredTShirt-2.jpg",
            "/images/product/men/t-shirts/multiLayeredTShirt-3.jpg",
            "/images/product/men/t-shirts/multiLayeredTShirt-4.jpg",
          ],
          previewImageUrl:
            "/images/product/men/t-shirts/multiLayeredTShirt-5.jpg",
        },
      ],
      count: 3,
    },
    {
      id: crypto.randomUUID(),
      name: "ХУДИ И СВИТЕРЫ",
      slug: "sweaters",
      list: [
        {
          id: crypto.randomUUID(),
          name: "ХУДИ ОВЕРСАЙЗ",
          slug: "oversizedHoodie",
          price: 9900,
          quantity: 10,
          imagesUrl: [
            "/images/product/men/sweaters/oversizedHoodie-1.jpg",
            "/images/product/men/sweaters/oversizedHoodie-2.jpg",
            "/images/product/men/sweaters/oversizedHoodie-3.jpg",
          ],
          previewImageUrl: "/images/product/men/sweaters/oversizedHoodie-5.jpg",
        },
        {
          id: crypto.randomUUID(),
          name: "СВИТЕР СИНИЙ",
          slug: "sweaterBlue",
          price: 9900,
          quantity: 10,
          imagesUrl: [
            "/images/product/men/sweaters/sweaterBlue-1.jpg",
            "/images/product/men/sweaters/sweaterBlue-2.jpg",
          ],
          previewImageUrl: "/images/product/men/sweaters/sweaterBlue-3.jpg",
        },
        {
          id: crypto.randomUUID(),
          name: "СВИТЕР СЕРЫЙ",
          slug: "sweaterGray",
          price: 9900,
          quantity: 10,
          imagesUrl: [
            "/images/product/men/sweaters/sweaterGray-1.jpg",
            "/images/product/men/sweaters/sweaterGray-2.jpg",
            "/images/product/men/sweaters/sweaterGray-3.jpg",
            "/images/product/men/sweaters/sweaterGray-4.jpg",
          ],
          previewImageUrl: "/images/product/men/sweaters/sweaterGray-5.jpg",
        },
      ],
      count: 3,
    },
    {
      id: crypto.randomUUID(),
      slug: "jackets",
      name: "ПИДЖАКИ",
      list: [
        {
          id: crypto.randomUUID(),
          name: "ПИДЖАК С МОЛНИЯМИ",
          slug: "jacketWithZippers",
          price: 9900,
          quantity: 10,
          imagesUrl: [
            "/images/product/men/jackets/jacketWithZippers-1.jpg",
            "/images/product/men/jackets/jacketWithZippers-2.jpg",
            "/images/product/men/jackets/jacketWithZippers-3.jpg",
            "/images/product/men/jackets/jacketWithZippers-4.jpg",
          ],
          previewImageUrl:
            "/images/product/men/jackets/jacketWithZippers-5.jpg",
        },
      ],
      count: 1,
    },
    {
      id: crypto.randomUUID(),
      slug: "outerwear",
      name: "ВЕРХНЯЯ ОДЕЖДА",
      list: [
        {
          id: crypto.randomUUID(),
          name: "ВАТНИК ОБЪЁМНЫЙ",
          slug: "woolQuiltedJacket",
          price: 9900,
          quantity: 10,
          imagesUrl: [
            "/images/product/men/outerwear/woolQuiltedJacket-1.jpg",
            "/images/product/men/outerwear/woolQuiltedJacket-2.jpg",
          ],
          previewImageUrl:
            "/images/product/men/outerwear/woolQuiltedJacket-3.jpg",
        },
        {
          id: crypto.randomUUID(),
          name: "БОМБЕР",
          slug: "oversizedBomberJacket",
          price: 9900,
          quantity: 10,
          imagesUrl: [
            "/images/product/men/outerwear/oversizedBomberJacket-1.jpg",
            "/images/product/men/outerwear/oversizedBomberJacket-2.jpg",
            "/images/product/men/outerwear/oversizedBomberJacket-3.jpg",
          ],
          previewImageUrl:
            "/images/product/men/outerwear/oversizedBomberJacket-4.jpg",
        },
      ],
      count: 1,
    },
    {
      id: crypto.randomUUID(),
      slug: "accessories",
      name: "АКСЕССУАРЫ",
      list: [
        {
          id: crypto.randomUUID(),
          name: "СУМКА-ЖИЛЕТКА",
          slug: "bagVest",
          price: 9900,
          quantity: 10,
          imagesUrl: [
            "/images/product/accessories/men-bagVest-1.jpg",
            "/images/product/accessories/men-bagVest-2.jpg",
            "/images/product/accessories/women-bagVest-1.jpg",
            "/images/product/accessories/women-bagVest-2.jpg",
          ],
          previewImageUrl: "/images/product/accessories/men-bagVest-3.jpg",
        },
        {
          id: crypto.randomUUID(),
          name: "СЪЁМНЫЙ КАПЮШОН С КАРМАНОМ",
          slug: "removableHoodWithCamouflage",
          price: 9900,
          quantity: 10,
          imagesUrl: [
            "/images/product/accessories/men-removableHoodWithCamouflage-1.jpg",
            "/images/product/accessories/men-removableHoodWithCamouflage-2.jpg",
            "/images/product/accessories/women-removableHoodWithCamouflage-1.jpg",
            "/images/product/accessories/women-removableHoodWithCamouflage-2.jpg",
          ],
          previewImageUrl:
            "/images/product/accessories/women-removableHoodWithCamouflage-3.jpg",
        },
        {
          id: crypto.randomUUID(),
          name: "ШАРФ",
          slug: "scarf",
          price: 9900,
          quantity: 10,
          imagesUrl: [
            "/images/product/accessories/men-scarfBlue-1.jpg",
            "/images/product/accessories/men-scarfBlue-2.jpg",
            "/images/product/accessories/men-scarfGray-1.jpg",
            "/images/product/accessories/women-scarfGray-1.jpg",
          ],
          previewImageUrl:
            "/images/product/accessories/women-removableHoodWithCamouflage-3.jpg",
        },
        {
          id: crypto.randomUUID(),
          name: "ШАПКА",
          slug: "cap",
          price: 9900,
          quantity: 10,
          imagesUrl: [
            "/images/product/accessories/men-cap-1.jpg",
            "/images/product/accessories/men-cap-2.jpg",
            "/images/product/accessories/women-cap-1.jpg",
            "/images/product/accessories/women-cap-2.jpg",
          ],
          previewImageUrl: "/images/product/accessories/women-cap-3.jpg",
        },
        {
          id: crypto.randomUUID(),
          name: "БАЛАКЛАВА",
          slug: "balaclava",
          price: 9900,
          quantity: 10,
          imagesUrl: [
            "/images/product/accessories/balaclava-1.jpg",
            "/images/product/accessories/balaclava-2.jpg",
            "/images/product/accessories/balaclava-3.jpg",
          ],
          previewImageUrl: "/images/product/accessories/balaclava-4.jpg",
        },
      ],
      count: 5,
    },
  ],
  categoriesWomen: [
    {
      id: crypto.randomUUID(),
      slug: "dresses",
      name: "ПЛАТЬЯ",
      list: [
        {
          id: crypto.randomUUID(),
          name: "ПЛАТЬЕ МАКСИ ТРЕХСЛОЙНОЕ",
          slug: "ThreeLayerMaxiDress",
          price: 9900,
          quantity: 10,
          imagesUrl: [
            "/images/product/women/dresses/ThreeLayerMaxiDress-1.jpg",
            "/images/product/women/dresses/ThreeLayerMaxiDress-2.jpg",
            "/images/product/women/dresses/ThreeLayerMaxiDress-3.jpg",
            "/images/product/women/dresses/ThreeLayerMaxiDress-4.jpg",
          ],
          previewImageUrl:
            "/images/product/women/dresses/ThreeLayerMaxiDress-1.jpg",
        },
      ],
      count: 1,
    },
    {
      id: crypto.randomUUID(),
      slug: "trousers",
      name: "БРЮКИ И ДЖИНСЫ",
      list: [
        {
          id: crypto.randomUUID(),
          name: "ДЖИНСЫ С ДВОЙНЫМ ПОЯСОМ",
          slug: "jeansWithDoubleBelt",
          price: 9900,
          quantity: 10,
          imagesUrl: [
            "/images/product/women/trousers/jeansWithDoubleBelt-1.jpg",
            "/images/product/women/trousers/jeansWithDoubleBelt-2.jpg",
            "/images/product/women/trousers/jeansWithDoubleBelt-3.jpg",
            "/images/product/women/trousers/jeansWithDoubleBelt-4.jpg",
          ],
          previewImageUrl:
            "/images/product/women/trousers/jeansWithDoubleBelt-1.jpg",
        },
        {
          id: crypto.randomUUID(),
          name: "ДЖИНСЫ КЛЁШ С ФАКТУРНЫМИ ШВАМИ",
          slug: "flaredJeans",
          price: 9900,
          quantity: 10,
          imagesUrl: [
            "/images/product/women/trousers/flaredJeans-1.jpg",
            "/images/product/women/trousers/flaredJeans-2.jpg",
            "/images/product/women/trousers/flaredJeans-3.jpg",
            "/images/product/women/trousers/flaredJeans-4.jpg",
          ],
          previewImageUrl: "/images/product/women/trousers/flaredJeans-1.jpg",
        },
        {
          id: crypto.randomUUID(),
          name: "БРЮКИ ПРЯМЫЕ ЖЕНСКИЕ",
          slug: "straightTrousers",
          price: 9900,
          quantity: 10,
          imagesUrl: [
            "/images/product/women/trousers/straightTrousers-1.jpg",
            "/images/product/women/trousers/straightTrousers-2.jpg",
            "/images/product/women/trousers/straightTrousers-3.jpg",
            "/images/product/women/trousers/straightTrousers-4.jpg",
          ],
          previewImageUrl:
            "/images/product/women/trousers/straightTrousers-1.jpg",
        },
        {
          id: crypto.randomUUID(),
          name: "БРЮКИ СВОБОДНЫЕ С ПОЯСОМ НА КАРАБИНЕ",
          slug: "looseTrousers",
          price: 9900,
          quantity: 10,
          imagesUrl: [
            "/images/product/women/trousers/looseTrousers-1.jpg",
            "/images/product/women/trousers/looseTrousers-2.jpg",
            "/images/product/women/trousers/looseTrousers-3.jpg",
            "/images/product/women/trousers/looseTrousers-4.jpg",
          ],
          previewImageUrl: "/images/product/women/trousers/looseTrousers-1.jpg",
        },
      ],
      count: 4,
    },
    {
      id: crypto.randomUUID(),
      slug: "skirts",
      name: "ЮБКИ",
      list: [
        {
          id: crypto.randomUUID(),
          name: "ЮБКА МИДИ АССИМЕТРИЧНАЯ",
          slug: "asymmetricalMidiSkirt",
          price: 9900,
          quantity: 10,
          imagesUrl: [
            "/images/product/women/skirts/asymmetricalMidiSkirt-1.jpg",
            "/images/product/women/skirts/asymmetricalMidiSkirt-2.jpg",
            "/images/product/women/skirts/asymmetricalMidiSkirt-3.jpg",
            "/images/product/women/skirts/asymmetricalMidiSkirt-4.jpg",
          ],
          previewImageUrl:
            "/images/product/women/skirts/asymmetricalMidiSkirt-1.jpg",
        },
        {
          id: crypto.randomUUID(),
          name: "ЮБКА МИНИ АССИМЕТРИЧНАЯ",
          slug: "asymmetricalMiniSkirt",
          price: 9900,
          quantity: 10,
          imagesUrl: [
            "/images/product/women/skirts/asymmetricalMiniSkirt-1.jpg",
            "/images/product/women/skirts/asymmetricalMiniSkirt-2.jpg",
            "/images/product/women/skirts/asymmetricalMiniSkirt-3.jpg",
            "/images/product/women/skirts/asymmetricalMiniSkirt-4.jpg",
          ],
          previewImageUrl:
            "/images/product/women/skirts/asymmetricalMiniSkirt-1.jpg",
        },
      ],
      count: 2,
    },
    {
      id: crypto.randomUUID(),
      slug: "sweaters",
      name: "СВИТЕРЫ",
      list: [
        {
          id: crypto.randomUUID(),
          name: "СВИТЕР СИНИЙ",
          slug: "sweaterBlue",
          price: 9900,
          quantity: 10,
          imagesUrl: [
            "/images/product/women/sweaters/sweaterBlue-1.jpg",
            "/images/product/women/sweaters/sweaterBlue-2.jpg",
          ],
          previewImageUrl: "/images/product/women/sweaters/sweaterBlue-1.jpg",
        },
        {
          id: crypto.randomUUID(),
          name: "СВИТЕР СЕРЫЙ",
          slug: "sweaterGray",
          price: 9900,
          quantity: 10,
          imagesUrl: [
            "/images/product/women/sweaters/sweaterGray-1.jpg",
            "/images/product/women/sweaters/sweaterGray-2.jpg",
          ],
          previewImageUrl: "/images/product/women/sweaters/sweaterGray-1.jpg",
        },
      ],
      count: 2,
    },
    {
      id: crypto.randomUUID(),
      slug: "jackets",
      name: "ЖАКЕТЫ",
      list: [
        {
          id: crypto.randomUUID(),
          name: "ЖАКЕТ АССИМЕТРИЧНЫЙ",
          slug: "asymmetricalJacket",
          price: 9900,
          quantity: 10,
          imagesUrl: [
            "/images/product/women/jackets/asymmetricalJacket-1.jpg",
            "/images/product/women/jackets/asymmetricalJacket-2.jpg",
            "/images/product/women/jackets/asymmetricalJacket-3.jpg",
            "/images/product/women/jackets/asymmetricalJacket-4.jpg",
          ],
          previewImageUrl:
            "/images/product/women/jackets/asymmetricalJacket-1.jpg",
        },
        {
          id: crypto.randomUUID(),
          name: "ЖАКЕТ УДЛИНЁННЫЙ С ПОЯСОМ",
          slug: "asymmetricalJacket",
          price: 9900,
          quantity: 10,
          imagesUrl: [
            "/images/product/women/jackets/elongatedJacketWithBelt-1.jpg",
            "/images/product/women/jackets/elongatedJacketWithBelt-2.jpg",
            "/images/product/women/jackets/elongatedJacketWithBelt-3.jpg",
            "/images/product/women/jackets/elongatedJacketWithBelt-4.jpg",
          ],
          previewImageUrl:
            "/images/product/women/jackets/elongatedJacketWithBelt-1.jpg",
        },
      ],
      count: 2,
    },
    {
      id: crypto.randomUUID(),
      slug: "tops",
      name: "ТОПЫ И ФУТБОЛКИ",
      list: [
        {
          id: crypto.randomUUID(),
          name: "ТОП СО ВСТАВКОЙ",
          slug: "topWithInsert",
          price: 9900,
          quantity: 10,
          imagesUrl: [
            "/images/product/women/tops/topWithInsert-1.jpg",
            "/images/product/women/tops/topWithInsert-2.jpg",
            "/images/product/women/tops/topWithInsert-3.jpg",
          ],
          previewImageUrl: "/images/product/women/tops/topWithInsert-3.jpg",
        },
        {
          id: crypto.randomUUID(),
          name: "ФУТБОЛКА С ФАКТУРНЫМИ ШВАМИ",
          slug: "TShirtWithTexturedSeams",
          price: 9900,
          quantity: 10,
          imagesUrl: [
            "/images/product/women/tops/TShirtWithTexturedSeams-1.jpg",
            "/images/product/women/tops/TShirtWithTexturedSeams-2.jpg",
            "/images/product/women/tops/TShirtWithTexturedSeams-3.jpg",
            "/images/product/women/tops/TShirtWithTexturedSeams-4.jpg",
          ],
          previewImageUrl:
            "/images/product/women/tops/TShirtWithTexturedSeams-1.jpg",
        },
        {
          id: crypto.randomUUID(),
          name: "МАЙКА ВЯЗАНАЯ",
          slug: "TShirtKnitted",
          price: 9900,
          quantity: 10,
          imagesUrl: [
            "/images/product/women/tops/TShirtKnitted-1.jpg",
            "/images/product/women/tops/TShirtKnitted-2.jpg",
            "/images/product/women/tops/TShirtKnitted-3.jpg",
          ],
          previewImageUrl: "/images/product/women/tops/TShirtKnitted-1.jpg",
        },
      ],
      count: 3,
    },
    {
      id: crypto.randomUUID(),
      slug: "shirts",
      name: "РУБАШКИ",
      list: [
        {
          id: crypto.randomUUID(),
          name: "РУБАШКА С КОКЕТКОЙ",
          slug: "shirtWithYoke",
          price: 9900,
          quantity: 10,
          imagesUrl: [
            "/images/product/women/shirts/shirtWithYoke-1.jpg",
            "/images/product/women/shirts/shirtWithYoke-2.jpg",
            "/images/product/women/shirts/shirtWithYoke-3.jpg",
            "/images/product/women/shirts/shirtWithYoke-4.jpg",
            "/images/product/women/shirts/shirtWithYoke-5.jpg",
          ],
          previewImageUrl: "/images/product/women/shirts/shirtWithYoke-5.jpg",
        },
      ],
      count: 1,
    },
    {
      id: crypto.randomUUID(),
      slug: "outerwear",
      name: "ВЕРХНЯЯ ОДЕЖДА",
      list: [
        {
          id: crypto.randomUUID(),
          name: "БОМБЕР ОВЕРСАЙЗ",
          slug: "oversizedBomberJacket",
          price: 9900,
          quantity: 10,
          imagesUrl: [
            "/images/product/women/outerwear/oversizedBomberJacket-1.jpg",
            "/images/product/women/outerwear/oversizedBomberJacket-2.jpg",
            "/images/product/women/outerwear/oversizedBomberJacket-3.jpg",
          ],
          previewImageUrl:
            "/images/product/women/outerwear/oversizedBomberJacket-4.jpg",
        },
        {
          id: crypto.randomUUID(),
          name: "ВАТНИК ИЗ ШЕРСТИ",
          slug: "woolQuiltedJacket",
          price: 9900,
          quantity: 10,
          imagesUrl: [
            "/images/product/women/outerwear/woolQuiltedJacket-1.jpg",
            "/images/product/women/outerwear/woolQuiltedJacket-2.jpg",
            "/images/product/women/outerwear/woolQuiltedJacket-3.jpg",
          ],
          previewImageUrl:
            "/images/product/women/outerwear/woolQuiltedJacket-4.jpg",
        },
      ],
      count: 2,
    },
    {
      id: crypto.randomUUID(),
      slug: "accessories",
      name: "АКСЕССУАРЫ",
      list: [
        {
          id: crypto.randomUUID(),
          name: "СУМКА-ЖИЛЕТКА",
          slug: "bagVest",
          price: 9900,
          quantity: 10,
          imagesUrl: [
            "/images/product/accessories/men-bagVest-1.jpg",
            "/images/product/accessories/men-bagVest-2.jpg",
            "/images/product/accessories/women-bagVest-1.jpg",
            "/images/product/accessories/women-bagVest-2.jpg",
          ],
          previewImageUrl: "/images/product/accessories/men-bagVest-3.jpg",
        },
        {
          id: crypto.randomUUID(),
          name: "СЪЁМНЫЙ КАПЮШОН С КАРМАНОМ",
          slug: "removableHoodWithCamouflage",
          price: 9900,
          quantity: 10,
          imagesUrl: [
            "/images/product/accessories/men-removableHoodWithCamouflage-1.jpg",
            "/images/product/accessories/men-removableHoodWithCamouflage-2.jpg",
            "/images/product/accessories/women-removableHoodWithCamouflage-1.jpg",
            "/images/product/accessories/women-removableHoodWithCamouflage-2.jpg",
          ],
          previewImageUrl:
            "/images/product/accessories/women-removableHoodWithCamouflage-3.jpg",
        },
        {
          id: crypto.randomUUID(),
          name: "ШАРФ",
          slug: "scarf",
          price: 9900,
          quantity: 10,
          imagesUrl: [
            "/images/product/accessories/men-scarfBlue-1.jpg",
            "/images/product/accessories/men-scarfBlue-2.jpg",
            "/images/product/accessories/men-scarfGray-1.jpg",
            "/images/product/accessories/women-scarfGray-1.jpg",
          ],
          previewImageUrl:
            "/images/product/accessories/women-removableHoodWithCamouflage-3.jpg",
        },
        {
          id: crypto.randomUUID(),
          name: "ШАПКА",
          slug: "cap",
          price: 9900,
          quantity: 10,
          imagesUrl: [
            "/images/product/accessories/men-cap-1.jpg",
            "/images/product/accessories/men-cap-2.jpg",
            "/images/product/accessories/women-cap-1.jpg",
            "/images/product/accessories/women-cap-2.jpg",
          ],
          previewImageUrl: "/images/product/accessories/women-cap-3.jpg",
        },
        {
          id: crypto.randomUUID(),
          name: "БАЛАКЛАВА",
          slug: "balaclava",
          price: 9900,
          quantity: 10,
          imagesUrl: [
            "/images/product/accessories/balaclava-1.jpg",
            "/images/product/accessories/balaclava-2.jpg",
            "/images/product/accessories/balaclava-3.jpg",
          ],
          previewImageUrl: "/images/product/accessories/balaclava-4.jpg",
        },
      ],
      count: 5,
    },
  ],

  accessoriesListAll: [
    {
      id: crypto.randomUUID(),
      name: "СУМКА-ЖИЛЕТКА",
      slug: "bagVest",
      price: 9900,
      quantity: 10,
      imagesUrl: [
        "/images/product/accessories/men-bagVest-1.jpg",
        "/images/product/accessories/men-bagVest-2.jpg",
        "/images/product/accessories/women-bagVest-1.jpg",
        "/images/product/accessories/women-bagVest-2.jpg",
      ],
      previewImageUrl: "/images/product/accessories/men-bagVest-3.jpg",
    },
    {
      id: crypto.randomUUID(),
      name: "СЪЁМНЫЙ КАПЮШОН С КАРМАНОМ",
      slug: "removableHoodWithCamouflage",
      price: 9900,
      quantity: 10,
      imagesUrl: [
        "/images/product/accessories/men-removableHoodWithCamouflage-1.jpg",
        "/images/product/accessories/men-removableHoodWithCamouflage-2.jpg",
        "/images/product/accessories/women-removableHoodWithCamouflage-1.jpg",
        "/images/product/accessories/women-removableHoodWithCamouflage-2.jpg",
      ],
      previewImageUrl:
        "/images/product/accessories/women-removableHoodWithCamouflage-3.jpg",
    },
    {
      id: crypto.randomUUID(),
      name: "ШАРФ",
      slug: "scarf",
      price: 9900,
      quantity: 10,
      imagesUrl: [
        "/images/product/accessories/men-scarfBlue-1.jpg",
        "/images/product/accessories/men-scarfBlue-2.jpg",
        "/images/product/accessories/men-scarfGray-1.jpg",
        "/images/product/accessories/women-scarfGray-1.jpg",
      ],
      previewImageUrl:
        "/images/product/accessories/women-removableHoodWithCamouflage-3.jpg",
    },
    {
      id: crypto.randomUUID(),
      name: "ШАПКА",
      slug: "cap",
      price: 9900,
      quantity: 10,
      imagesUrl: [
        "/images/product/accessories/men-cap-1.jpg",
        "/images/product/accessories/men-cap-2.jpg",
        "/images/product/accessories/women-cap-1.jpg",
        "/images/product/accessories/women-cap-2.jpg",
      ],
      previewImageUrl: "/images/product/accessories/women-cap-3.jpg",
    },
    {
      id: crypto.randomUUID(),
      name: "БАЛАКЛАВА",
      slug: "balaclava",
      price: 9900,
      quantity: 10,
      imagesUrl: [
        "/images/product/accessories/balaclava-1.jpg",
        "/images/product/accessories/balaclava-2.jpg",
        "/images/product/accessories/balaclava-3.jpg",
      ],
      previewImageUrl: "/images/product/accessories/balaclava-4.jpg",
    },
  ],
};
