import { StoreProvider } from "@/store/storeProvider";
import { ReactNode } from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../shared/styles/globals.css";
import ContainerPage from "@/widgets/Layout/ContainerPage";
import Header from "@/widgets/Layout/Header";
import Main from "@/widgets/Layout/Main";
import Footer from "@/widgets/Layout/Footer";

const interFont = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <StoreProvider>
      <html lang="en">
        <body className={`${interFont.className} antialiased`}>
          <ContainerPage>
            <Header />
            <Main>{children}</Main>
            <Footer />
          </ContainerPage>
        </body>
      </html>
    </StoreProvider>
  );
}
